# Generated by Django 4.0.6 on 2022-07-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_admin_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, upload_to='static/images/author'),
        ),
    ]
